language: python
python:
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements_for_test.txt
# command to run tests
script:
- ./scripts/run_tests.sh
