language: python
sudo: required
dist: trusty
python:
  - "3.5"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements_for_test.txt
  - . $HOME/.nvm/nvm.sh
  - rm -rf node_modules
  - npm cache clean
  - nvm install v5.4.1
  - npm install
# command to run tests
script:
- ./scripts/run_tests.sh

notifications:
  slack: digitaleq:LDxJXRGeVmg3PpdUhp90eY3Z
