language: python
python:
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements_for_test.txt
# command to run tests
script:
- ./scripts/run_tests.sh

# Front-end config
# 
# language: node_js
# node_js:
#   - "0.10"
# before_script:
#   - npm install -g gulp
# script: gulp
