language: python
sudo: required
dist: trusty
python:
- '3.5'
env:
- EQ_SCHEMA_BUCKET=""
before_install:
# install Chromedriver
- export CHROME_BIN=/usr/bin/google-chrome
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sudo apt-get update
- sudo apt-get install -y libappindicator1 fonts-liberation
- wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
- sudo dpkg -i google-chrome*.deb
# Repo for newer Node.js versions
- curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
# Repo for Yarn
- sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
- echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
- sudo apt-get update -qq
- sudo apt-get install -y -qq yarn
cache:
  directories:
  - $HOME/.yarn-cache
install:
- ". $HOME/.nvm/nvm.sh"
- nvm install v6.9.1
- pip install -U pip wheel
- pip install --require-hashes -r requirements.txt
- pip install -r requirements_for_test.txt
before_script:
- yarn compile
- "./scripts/run_app.sh"
script:
- "./scripts/run_tests.sh"
# fail travis if under X% test coverage
- coverage report --fail-under=77
notifications:
- slack: digitaleq:LDxJXRGeVmg3PpdUhp90eY3Z
after_success:
- bash <(curl -s https://codecov.io/bash)
branches:
  only:
    - master
