name: Test

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - uses: actions/setup-node@v1
        with:
          node-version: '8.16.0'
      - name: Install apt Dependencies
        run: sudo apt-get install libsnappy-dev libgconf-2-4 google-chrome-stable
      - name: Write App Version
        run: printf $(git rev-parse HEAD) > .application-version
      - name: Install Pipenv
        run: pip install pipenv==2018.11.26
      - name: Cache virtualenv
        uses: actions/cache@v1
        with:
            path: ~/.local/share/virtualenvs/
            key: ${{ runner.os }}-virtualenvs-${{ hashFiles('Pipfile.lock') }}
      - name: Install Virtual Environment
        run: pipenv install --dev
      - name: Load Schemas
        run: ./scripts/load_schemas.sh
      - name: Load Templates
        run: ./scripts/load_templates.sh
      - name: Run Travis Steps
        run: ln -sf .development.env .env
      - name: Running translation tests
        run: pipenv run python -m scripts.extract_translation_templates --test
      - name: Running lint tests
        run: pipenv run ./scripts/run_lint.sh
      - name: Running unit tests
        run: pipenv run ./scripts/run_tests_unit.sh
  test-schemas:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Load Schemas
          run: ./scripts/load_schemas.sh
        - name: Running schema tests
          run: ./scripts/test_schemas.sh
